## Nome: Leonardo Valadão. NUSP: 10299437

# 2º Programa: Solução de Sistemas de Equações Lineares

### Disciplina: Cálculo Numérico com Aplicações em Física. Docente: Arnaldo Gammal.

**Observe o circuito abaixo.** <br>
![title](./circuit.png)
**Dados $R_1=8\Omega$, $R_2=5\Omega$, $R_3=5\Omega$, $R_4=1\Omega$, $U_1=22V$, $U_2=7V$, $U_3=3V$.**

**a) Aplique as leis de Kirchhoff no sistema acima e obtenha três equações lineramente indepentes para $I_1$, $I_2$, $I_3$ na forma**

<center>
$\left[\begin{array}{ccc}
0 & 5 & -1\\
13 & 0 & 1\\
1 & -1 & -1\\
\end{array}\right]$
$\left[\begin{array}{ccc}
I_1\\
I_2\\
I_3\\
\end{array}\right]$
=
$\left[\begin{array}{ccc}
4\\
15\\
0\\
\end{array}\right]$
</center>

Lei de Kirchhoff para circuitos: $\sum_{k=1}^n I_k=0$ <br>
Lei de Kirchhoff para voltagem: $\sum_{k=1}^n V_k=0$ <br>
Lei de Ohm: $V=R \times I$

Com o circuito acima, podemos montar para cada <i>loop</i>, utilizando a Lei de Kirchhoff para voltagem e a Lei de Ohm,  as seguintes equações:<br>
$-I_1R_1-U_2-R_4I_3-I_1R_2+U_1=0$ <br>
$-I_2R_3-U_3+U_2+I_3R_4=0$<br>
E com a Lei de Kirchhoff para circuitos: <br>
$I_1-I_2-I_3=0$

Trabalhando com as duas primeiras equações, temos: <br>
$-8I_1-7-I_3-5I_1+22=0$ <br>
$5I_2-3+7+I_3=0$

Manipulando estas duas equações e considerando a terceira, temos:<br>
$13I_1+I_3=15$<br>
$5I_2-I_3=4$<br>
$I_1-I_2-I_3=0$<br>

Que se transformam na matriz:
<center>
$\left[\begin{array}{ccc}
0 & 5 & -1\\
13 & 0 & 1\\
1 & -1 & -1\\
\end{array}\right]$
$\left[\begin{array}{ccc}
I_1\\
I_2\\
I_3\\
\end{array}\right]$
=
$\left[\begin{array}{ccc}
4\\
15\\
0\\
\end{array}\right]$
</center>

**b) Construa um programa que resolva o sistema acima pelo método de Eliminaçao de Gauss usando pivotamento parcial. Imprima também as matrizes intermediárias até chegar na matriz triangular superior. O programa deve ser capaz de resolver $n$ equações.**

In [1]:
# Definir algoritmo
import numpy as np

# Definir matriz
matriz = [
    [0, 5, -1, 4], 
    [13, 0, 1, 15],
    [1, -1, -1, 0]]

# Definir função
def gauss(M):
    # Número de colunas
    cols = len(M)
    
    # Para cada coluna...
    for i in range(0, cols):
        print('Iteração nº {:.0f}:\n'.format(i),np.array(M).reshape(3,4),'\n\n')
        el_max = abs(M[i][i]) #Elemento da Diagonal
        lin_max = i #Linha atual
        # Pra cada linha abaixo...
        for k in range(i + 1, cols):
            # Se o elemento atual for maior que a diagonal...
            if abs(M[k][i]) > el_max:
                el_max = abs(M[k][i]) # Atualiza elemento máximo
                lin_max = k # Atualiza linha

        # Trocar linha máxima por linha atual
        for k in range(i, cols + 1):
            tmp = M[lin_max][k]
            M[lin_max][k] = M[i][k]
            M[i][k] = tmp

        # Transformar colunas abaixo desta em zero
        # Pra cada linha abaixo...
        for k in range(i + 1, cols):
            # Dividir pela diagonal != 0
            c = -M[k][i] / M[i][i]
            # Pra cada linha...
            for j in range(i, cols + 1):
                # Se linha = coluna, =0
                if i == j:
                    M[k][j] = 0
                    # Se não, somar e multiplicar por escalar
                else:
                    M[k][j] += c * M[i][j]

    # Resolver equação para matriz triangular superior
    x = [0 for i in range(cols)]
    for i in range(cols - 1, -1, -1):
        x[i] = M[i][cols] / M[i][i] # Dividir resultado por diagonal
        for k in range(i - 1, -1, -1):
            M[k][cols] -= M[k][i] * x[i]
    return x

print('Matrizes intermediárias:\n==================')
r = gauss(matriz)
print('Resultados: \nI_1 = {:.3f} \nI_2 = {:.3f} \nI_3 = {:.3f}'.format(r[0], r[1], r[2]))

Matrizes intermediárias:
Iteração nº 0:
 [[ 0  5 -1  4]
 [13  0  1 15]
 [ 1 -1 -1  0]] 


Iteração nº 1:
 [[13.          0.          1.         15.        ]
 [ 0.          5.         -1.          4.        ]
 [ 0.         -1.         -1.07692308 -1.15384615]] 


Iteração nº 2:
 [[13.          0.          1.         15.        ]
 [ 0.          5.         -1.          4.        ]
 [ 0.          0.         -1.27692308 -0.35384615]] 


Resultados: 
I_1 = 1.133 
I_2 = 0.855 
I_3 = 0.277


**c) Permute as duas primeiras linhas do sistema (1) e construa um programa que resolva o sistema pelo método de Jacobi, usando um critério de parada max $|x_i^{(k+1)}-x_i^{(k)}|<\varepsilon$ para $i=1, ..., n$, $\varepsilon=10^{-4}$ e $k$ é o número da iteração. O programa deve imprimir tabelas contendo $k$, valores de $I_1$, $I_2$, $I_3$ e erro mostrando a convergência. O programa deve ser capaz de resolver sistemas com $n$ equações.**

In [2]:
# Definir matriz já permutada
matriz = [[13, 0, 1, 15], 
          [0, 5, -1, 4],
          [1, -1, -1, 0]]

def jacobi(M, initial_guess=[1,1,1], epsilon=10e-4):
    # Definir x e erro inicial
    x = initial_guess
    err = np.inf
    k=0
    
    # Critério de parada
    while err > epsilon:
        # Guardar parâmetros anteriores
        x_old = tuple(x)
        x_new = [0 for i in x]
        
        # Fazer o novo vetor
        for linha in range(len(M)):
            # Definir parâmetros da linha
            ann = M[linha][linha]
            bn = M[linha][-1]
            an = M[linha][:-1]
            
            # Soma de aij*xj, j!=i
            s=0
            for el in range(len(M[linha])-1):
                if not el==linha:
                    s = s+an[el]*x[el]

            # Cálculo de xn
            x_new[linha] = 1/ann * (bn - s)
        # Uma vez que saio do loop de cada variável, posso atualizar meus resultados
        x = x_new
            
        # Definir erro
        l_err = [abs(a - b) for a, b in zip(x_new, x_old)]
        err = max(l_err)
        
        # Imprimir tabela
        print('k: {:.0f} | I_1: {:.3f} | I_2: {:.3f} | I_3: {:.3f} | Erro: {:.5f}'.format(k, x[0], x[1], x[2], err))
        k+=1
    return(x)
        
        
print('Tabela de iterações:\n======================')
r = jacobi(matriz,initial_guess=[1,1,1])
print('Resultados: \nI_1 = {:.5f} \nI_2 = {:.5f} \nI_3 = {:.5f}'.format(r[0], r[1], r[2]))

Tabela de iterações:
k: 0 | I_1: 1.077 | I_2: 1.000 | I_3: -0.000 | Erro: 1.00000
k: 1 | I_1: 1.154 | I_2: 0.800 | I_3: 0.077 | Erro: 0.20000
k: 2 | I_1: 1.148 | I_2: 0.815 | I_3: 0.354 | Erro: 0.27692
k: 3 | I_1: 1.127 | I_2: 0.871 | I_3: 0.333 | Erro: 0.05538
k: 4 | I_1: 1.128 | I_2: 0.867 | I_3: 0.256 | Erro: 0.07669
k: 5 | I_1: 1.134 | I_2: 0.851 | I_3: 0.262 | Erro: 0.01534
k: 6 | I_1: 1.134 | I_2: 0.852 | I_3: 0.283 | Erro: 0.02124
k: 7 | I_1: 1.132 | I_2: 0.857 | I_3: 0.281 | Erro: 0.00425
k: 8 | I_1: 1.132 | I_2: 0.856 | I_3: 0.275 | Erro: 0.00588
k: 9 | I_1: 1.133 | I_2: 0.855 | I_3: 0.276 | Erro: 0.00118
k: 10 | I_1: 1.133 | I_2: 0.855 | I_3: 0.278 | Erro: 0.00163
k: 11 | I_1: 1.132 | I_2: 0.856 | I_3: 0.277 | Erro: 0.00033
Resultados: 
I_1 = 1.13250 
I_2 = 0.85551 
I_3 = 0.27743


Nota: Este programa resolve $n$ equações, mas não imprime iterações para $n$ variáveis.

**d) Repita o item c) usando o método de Gauss-Seidel.**

Pela semelhança entre os métodos, copiei o método anterior e modifiquei a definição de $x_n$ (x[linha]). Antes eu precisava guardar um x_new para realizar as operações para cada variável sem alterar o valor das outras. Agora eu atualizo tudo no mesmo vetor x, logo assim que uma variável muda, ela já entra no cálculo da próxima variável.

In [5]:
import numpy as np

# Definir matriz já permutada
matriz = [[13, 0, 1, 15], 
          [0, 5, -1, 4],
          [1, -1, -1, 0]]

# Definir função
def gauss_seidel(M, initial_guess=[1,1,1]):
    '''M=Matriz n x n+1, a última coluna é o vetor b. initial_guess é uma lista com chutes iniciais para x'''
    # Definir x e erro inicial
    x = initial_guess
    
    # Critério de parada
    for i in range(9):
        # Guardar parâmetros anteriores
        x_old = tuple(x)
        
        # Fazer o novo vetor
        for linha in range(len(M)):
            # Definir parâmetros da linha
            ann = M[linha][linha]
            bn = M[linha][-1]
            an = M[linha][:-1]

            # Soma de aij*xj, j!=i
            s=0
            for el in range(len(M[linha])-1):
                if not el==linha:
                    s = s+an[el]*x[el]

            # Cálculo de xn
            x[linha] = 1/ann * (bn - s)
    print(x)
    return(x)

print('Tabela de iterações:\n======================')
r = gauss_seidel(matriz)
print('Resultados: \nI_1 = {:.5f} \nI_2 = {:.5f} \nI_3 = {:.5f}'.format(r[0], r[1], r[2]))

Tabela de iterações:
[1.1325281973769439, 0.8554266868199462, 0.2771015105569977]
Resultados: 
I_1 = 1.13253 
I_2 = 0.85543 
I_3 = 0.27710
